user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

# --- УРОВЕНЬ L4 (TCP PROXYING) ---
stream {
    # Карта распределения трафика на основе SNI (домена в запросе клиента)
    map $ssl_preread_server_name $backend_gateway {
        # Если клиент идет в админку или за подпиской:
        panel.xxx.duckdns.org      127.0.0.1:4443; 
        sub.xxx.duckdns.org        127.0.0.1:4443;
        
        # Если клиент маскируется под Reality (указывает сайт-маскировку):
        yahoo.com                  3x-ui:8443; 
        
        # Защита: сканеры по IP или левые домены уходят на пустую веб-заглушку
        default                    127.0.0.1:4443;
    }

    server {
        listen 443; # Nginx слушает внешний порт 443 сервера
        listen [::]:443;
        
        proxy_pass $backend_gateway; # Перенаправляем сырой TCP поток по результатам map
        ssl_preread on;              # Включаем анализ SNI без дешифрации трафика
    }
}

# --- УРОВЕНЬ L7 (HTTP/HTTPS ВЕБ-СЕРВИСЫ) ---
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Подключаем наши настройки сайтов (админку и подписки)
    include /etc/nginx/conf.d/*.conf;
}

