server {
    # Слушаем внутренний порт, куда stream-модуль перенаправляет веб-трафик
    listen 127.0.0.1:4443 ssl http2;
    server_name panel.xxx.duckdns.org sub.xxx.duckdns.org;

    # Пути к нашему Wildcard-сертификату, который генерирует контейнер Certbot
    ssl_certificate /etc/letsencrypt/live/xxx.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx.duckdns.org/privkey.pem;

    # Строгие настройки безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # 1. Проксирование админ-панели 3X-UI
    location /admin/ {
        # Обращаемся к контейнеру панели по его Docker-имени и внутреннему порту
        proxy_pass http://3x-ui:32180;
        
        # Передаем реальные заголовки, чтобы панель видела IP клиентов, а не IP докера
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Проксирование службы подписок
    location /sub/ {
        proxy_pass http://3x-ui:32196;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Дефолтная заглушка (если зашли на корень домена без путей /admin/ или /sub/)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

